name: Atualizar README

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Atualizar Estat√≠sticas e √öltimo Commit
        uses: kevinzunigacuellar/github-profile-readme-generator@2.0.0
        with:
          username: andretallens
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "ü§ñ Atualiza√ß√£o autom√°tica do README (Estat√≠sticas e √öltimo Commit)"
          # Configura√ß√£o de Estat√≠sticas
          stats_enabled: true
          stats_theme: radical
          stats_exclude_repo: ""
          # Configura√ß√£o do √öltimo Commit
          latest_commit_enabled: true
          latest_commit_title: "‚≠ê √öltimo Destaque/Commit"
          latest_commit_max_days: 365
          latest_commit_count: 1
          latest_commit_type: "list"

      - name: Commit e Push das altera√ß√µes do README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ü§ñ Atualiza√ß√£o autom√°tica do README (Estat√≠sticas e √öltimo Commit)"
